link: "http://rubyonrails.org/"
contact_link: "https://www.railstutorial.org/contact"
help_link: "https://www.railstutorial.org/help"
book_link: "https://www.railstutorial.org/book"
news_link: "http://news.railstutorial.org/"
michael_hartl_link: "http://www.michaelhartl.com/"
